call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-surround'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'scrooloose/nerdtree'
Plug 'terryma/vim-multiple-cursors'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
call plug#end()

" map <C-n> :NERDTreeToggle<CR>

autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Settings
set tabstop=4                   " Indentation every 4 cols
set shiftwidth=4                " Tab = 4 spaces
set expandtab                   " Spaces > tabs
set smartindent                 " Smarter indenting
set showmatch                   " Show matching parens
set syntax=on                   " Syntax highlighting
set ff=unix                     " Unix file format
set showcmd                     " Show commands as they are typed
set grepprg=/bin/grep           " grep to use
set wrap                        " Soft wrapping at window edge
set showbreak=+                 " Break indication character
set backup                      " Turn on back ups
set modeline
set backupdir=~/.tmp/vim_backup " Vim backups
set dir=~/.tmp/vim_swap         " Vim swap files
set tw=79
